Repository 7Factor/terraform-aws-concourse, pull requests merged in 2024-03, with the labels that each got.

#39 Automate releases for Terraform Registry.
  .github/workflows/release.yml
  .github/workflows/require_label.yml
  CONTRIBUTING.md
  README.md
Labels: release:major

#40 Merge release automation into correct branch
  .github/workflows/release.yml
  .github/workflows/require_label.yml
  CONTRIBUTING.md
  README.md
Labels: release:major

#41 Permit non-major release automation for master branch.
  .github/workflows/release.yml
  .github/workflows/require_label.yml
Labels: release:patch

#37 Update the `base_ami` filter to use the `base_ami_name_filter` variable
  main.tf
  variables.tf
Labels: release:minor

#44 Add variable for setting feature flags on Concourse workers.
  asg.tf
  templates/worker_user_data.sh
  worker_variables.tf
Labels: release:minor

#45 Switch Concourse worker runtime to containerd.
  templates/worker_user_data.sh
Labels: release:minor

#46 Terraform the SSH keys instead of manually generating them.
  asg.tf
  keys.tf
  web_variables.tf
  worker_variables.tf
Labels: release:minor

#47 Add LB zone id to outputs.
  outputs.tf
Labels: release:minor

#48 Enable Concourse metrics collection in CloudWatch.
  asg.tf
  cloudwatch.tf
  config/cw_agent_config.json
  config/cw_metrics_config.json
  config/cw_prometheus_config.json
  config/prometheus_config.yml
  iam.tf
  main.tf
  s3.tf
  templates/cw_agent_init.sh
  templates/cw_agent_metrics_init.sh
  templates/cw_agent_prometheus_init.sh
  templates/web_user_data.sh
  templates/worker_user_data.sh
  variables.tf
Labels: release:minor
